import Head from 'next/head'
import Image from 'next/image'
import BalanceCard from '../src/components/BalanceCard/BalanceCard'
import { ContentContainer } from '../src/components/ContentContainer'
import { Header } from '../src/components/Header'
import { GlobalStyle } from '../styles/global'
import { Box } from '../src/ui'
import { StakeCard, BuyCard, RewardsTable } from '../src/components'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Royal token</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStyle />
      <Header />
      <Box m="20px 0 0 0">
        <ContentContainer>
          <Box type="grid" columns="2" columnMinSize="0" gap="20px">
            <BuyCard />
            <StakeCard />
          </Box>
          <RewardsTable />
        </ContentContainer>
      </Box>
    </div>
  )
}
